# Generated by Django 5.1.3 on 2024-11-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_management', '0003_tokenblacklistblacklistedtoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MmsTripActivity',
            fields=[
                ('tripactivityid', models.IntegerField(db_comment='A unique identifier for each record in the trip_activity junction table. This serves as the primary key and distinguishes each trip-activity relationship.', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mms_trip_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MmsTripRestaurant',
            fields=[
                ('restauranttripid', models.IntegerField(db_comment='A unique identifier for each record in the trip_restaurant junction table. This serves as the primary key and uniquely identifies the relationship between a trip and a restaurant.', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mms_trip_restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MmsTripRoom',
            fields=[
                ('triproomid', models.IntegerField(db_comment='A unique identifier for the association between a trip and a specific room allocation. This ID links a particular room to a specific trip, allowing the tracking of room assignments for each trip. It is used to map rooms to the trips they are associated with, facilitating room reservations and occupancy management for each trip.', primary_key=True, serialize=False)),
                ('roomsaleprice', models.DecimalField(db_comment='Room sale price for that particular trip', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'mms_trip_room',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthtokenToken',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='TokenBlacklistBlacklistedtoken',
        ),
        migrations.DeleteModel(
            name='TokenBlacklistOutstandingtoken',
        ),
    ]
