# Generated by Django 5.1.3 on 2024-11-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_management', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='mms_user_profile',
        ),
    ]
