# Generated by Django 5.1.3 on 2024-12-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_management', '0009_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MmsShip',
            fields=[
                ('shipid', models.AutoField(db_comment='Unique identifier for every ship', primary_key=True, serialize=False)),
                ('shipname', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=45)),
                ('description', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=150)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'mms_ship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MmsShipActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mms_ship_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MmsShipRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mms_ship_restaurant',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MmsActivityPsngr',
        ),
        migrations.DeleteModel(
            name='MmsRestaurantPsngr',
        ),
        migrations.DeleteModel(
            name='MmsTripActivity',
        ),
        migrations.DeleteModel(
            name='MmsTripRestaurant',
        ),
    ]
