# Generated by Django 5.1.3 on 2024-12-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_management', '0010_mmsship_mmsshipactivity_mmsshiprestaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MmsShipRoom',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('availability', models.IntegerField()),
            ],
            options={
                'db_table': 'mms_ship_room',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MmsTripRoom',
        ),
    ]
