# Generated by Django 5.1.3 on 2024-12-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_management', '0011_mmsshiproom_delete_mmstriproom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MmsTripPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mms_trip_package',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MmsPsngrPackage',
        ),
    ]
