# Generated by Django 5.1.3 on 2024-12-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_management', '0012_mmstrippackage_delete_mmspsngrpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MmsTripRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamicprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isbooked', models.IntegerField()),
            ],
            options={
                'db_table': 'mms_trip_room',
                'managed': False,
            },
        ),
    ]
