# Generated by Django 5.1.3 on 2024-12-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise_management', '0013_mmstriproom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MmsBookingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mms_booking_package',
                'managed': False,
            },
        ),
    ]
